spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
#            driver-class-name: org.postgresql.Driver
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.146.129:3306/iot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true   #办公网络||测试服||正式服专用
#            url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true   #办公网络||测试服||正式服专用
#            driver-class-name: org.postgresql.Driver
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            url: jdbc:mysql://10.0.22.66:4000/yanghu_sensor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true   #VPN连接深信服时专用
            username: test1
            password: test1
#            username: root
#            password: study!123
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
#        dynamic:
#            primary: master
#
#        master:
#          url: jdbc:mysql://iot.gstar-info.com:3306/iot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#          username: gstar_db
#          password: gstar_DB!@#$%67890
#          driver-class-name: com.mysql.cj.jdbc.Driver
#
#        slave1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://10.0.22.66:4000/yanghu_sensor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#          username: yanghu
#          password: LaMbom!x1

#    autoconfigure:
#        exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure


###多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.0.22.66:4000/yanghu_sensor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: yanghu
#      password: LaMbom!x1
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456
